# Generated by Django 5.1.5 on 2025-02-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novos_dizimistas', '0002_novodizimista_sistema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novodizimista',
            options={},
        ),
    ]
