# Generated by Django 5.1.5 on 2025-01-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novos_dizimistas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novodizimista',
            name='sistema',
            field=models.IntegerField(null=True),
        ),
    ]
