# Generated by Django 5.1.4 on 2025-01-11 23:08

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovoDizimista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paroquia', models.IntegerField()),
                ('ficha', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('phone_permission', models.BooleanField(default=True)),
                ('email_permission', models.BooleanField(default=True)),
                ('situacao', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
            ],
            options={
                'db_table': 'tb_novos_dizimistas',
                'permissions': [('can_view_novoDizimista', 'Can view novo dizimista'), ('can_edit_novoDizimista', 'Can edit novo dizimista')],
                'unique_together': {('id_paroquia', 'ficha')},
            },
        ),
    ]
