# Generated by Django 5.1.4 on 2025-01-11 23:08

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novos_dizimistas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novodizimista',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='novodizimista',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
