# Generated by Django 5.1.4 on 2025-01-14 18:50

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paroquia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dizimista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('phone_permission', models.BooleanField(default=True)),
                ('email_permission', models.BooleanField(default=True)),
                ('situacao', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('id_paroquia', models.ForeignKey(db_column='id_paroquia', null=True, on_delete=django.db.models.deletion.CASCADE, to='paroquia.paroquia')),
            ],
            options={
                'db_table': 'tb_dizimistas',
                'permissions': [('can_view_dizimista', 'Can view dizimista'), ('can_edit_dizimista', 'Can edit dizimista')],
            },
        ),
    ]
