# Generated by Django 5.1.4 on 2025-01-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dizimista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paroquia', models.IntegerField()),
                ('ficha', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('situacao', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
            ],
            options={
                'db_table': 'tb_dizimistas',
                'permissions': [('can_view_dizimista', 'Can view dizimista'), ('can_edit_dizimista', 'Can edit dizimista')],
                'unique_together': {('id_paroquia', 'ficha')},
            },
        ),
    ]
