# Generated by Django 5.1.4 on 2025-01-11 23:08

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dizimistas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dizimista',
            name='email_permission',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dizimista',
            name='phone_permission',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dizimista',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
