# Generated by Django 5.1.5 on 2025-02-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dizimistas', '0002_dizimista_sistema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dizimista',
            options={},
        ),
    ]
